### ISSUE TITLE
Some English:Italian pairs aren't correct

### ISSUE THREAD

**Issue by jungaretti** [joshspicer/widgetkit-daily-language#6]
Several of the English:Italian pairs are flipped and offset:

- https://github.com/joshspicer/widgetkit-daily-language/blob/dfa7fb1405d67140899907824215375c88add728/DailyWord/Languages/Italian.swift#L548-L598
- https://github.com/joshspicer/widgetkit-daily-language/blob/dfa7fb1405d67140899907824215375c88add728/DailyWord/Languages/Italian.swift#L787-L819

I can submit a PR for this soon 😸

**Comment by joshspicer** [comment]
how strange! IIRC I used [something similar to this script](https://github.com/joshspicer/widgetkit-daily-language/blob/main/extract.py) to scape the words.  Wonder how some got flipped 🤔
